fix: Resolve NoSuchFileException by applying Develocity plugin in settings.gradle
Fixed the windows build error caused by the Develocity plugin failing to access the build scan data
 directory, resulting in a `NoSuchFileException`. This issue was resolved by adding the
 `com.gradle.develocity` plugin to `settings.gradle`.

Error Message:
java.nio.file.NoSuchFileException: D:\a\.gradle\build-scan-data\3.18.2

Cause:
 - The Develocity plugin was missing. Applying it in `settings.gradle` ensures it is configured for the
 entire build,  preventing access issues with build scan data.

- The Develocity Gradle plugin enables integration with Develocity and scans.gradle.com.
  The Develocity plugin must be applied to the settings (was applied to a project)

Changes:
  - Removed the Develocity plugin application from `build.gradle`.
  - Added the Develocity plugin application to `settings.gradle`.

Affected Files:
    - `settings.gradle`